[package]
name = "rust_deep_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
moka = { version = "0.11", features = ["future"] }
json = { package = "serde_json", version = "1.0" }
serde = { version = "1.0", features = ["derive"] }

rocket = { version = "=0.5.0-rc.3", features = ["json"] }
