[package]
name = "rust_deep_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
json = { package = "serde_json", version = "1.0" }

rocket = { version = "0.5.0-rc.3", features = ["json"] }
