[package]
name = "rust-docker-isolation-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
moka = { version = "0.11", features = ["future"] }
serde = { version = "1.0", features = ["derive"] }

rocket = { version = "=0.5.0-rc.3", features = ["json"] }
json = { version = "1.0", package = "serde_json", features = ["raw_value"] }

[profile.release]
debug = true
incremental = true
lto = "thin"

[profile.release-strip]
inherits = "release"
strip = "symbols"
codegen-units = 1
lto = "fat"
