name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: ${{matrix.rust}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        rust: [stable, nightly]
        os: [ubuntu]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          # we check that provider `stable` compatible
          # but now scripts runtime require some nightly features
          toolchain: nightly
      - run: cargo install rust-script
      - run: cargo +${{matrix.rust}} test

  build:
    name: ${{matrix.target || 'native'}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{matrix.target}}
      - run: cargo check

  miri:
    name: Miri
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: -Zmiri-strict-provenance
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@miri
      - run: cargo miri setup
      - run: cargo miri test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@clippy
      # later try to add `-Dclippy::pedantic`
      - run: cargo clippy --tests -- -Dclippy::all
